### ISSUE TITLE
In game chat

### ISSUE THREAD

**Issue by Prulon** [BioLogIn001/spellweavers-engine#47]
**Issue**:
First thing I felt missing when playing the game was the in game chat, I believe it is a critical component for success

**Comment by BioLogIn001** [comment]
Thanks! Yes, chat is indeed on the menu. 

I've made a thread on Reddit about development plans for the web version, let's have feature requests and discussion there for now: https://www.reddit.com/r/Spellweavers/comments/1ain2xb/development_plans_feature_requests/

I'd like to keep this repo dedicated to core game engine, which is not affected by any web functionality. I have a separate repo for the web version, but I am not sure if this is a good idea to open it for everyone; hence let's keep it to Reddit for now.
