### ISSUE TITLE
Minor UX issues to make it more playable

### ISSUE THREAD

**Issue by Prulon** [BioLogIn001/spellweavers-engine#48]
1. After you submit orders, if the other player has already submitted orders and a new turn is ready --> go directly to that turn.
2. The split between created and ongoing games is very confusing. Better merge them to 1 list, and add status: e.g. Pending / Ready / Waiting. In the app we did it with Waiting to start / Waiting for <player> / Ready

**Comment by BioLogIn001** [comment]
1. Agreed. Not sure if it warrants immediate fix (it is not quite as easy as it might seem), or if it should be postponed and replaced with responsive UI (= JSON = no page reloads) in future.
2. Sure, we can discuss it. If people would feel this way, this can be easily reworked. Then again, not sure if it should be addressed immediately or if it should be done as a part of UI rework.

Again, let's move the UI / UX discussion to Reddit for now.
