### ISSUE TITLE
Bug: Counterspell doesn't work on summoning

### ISSUE THREAD

**Issue by Prulon** [BioLogIn001/spellweavers-engine#49]
Issue:
When opponent casts a summon, and you cast counter at opponent, then the monster shouldn't be summoned.
Currently this doesn't work right, see https://spellweavers.gg/matches/2

**Comment by BioLogIn001** [comment]
Sorry, but it works as intended - I targeted the ogre summon at my goblin, and your counterspell targeted me. 

You could have countered the ogre by setting counterspell target to my goblin, that would have worked (but would also give my goblin a shield, so),

Also please let's switch to Reddit for now - this is the wrong repository to discuss the web version.

**Comment by Prulon** [comment]
you are right, I didn't notice you targeted the goblin
