### ISSUE TITLE
Ready game indication

### ISSUE THREAD

**Issue by Prulon** [BioLogIn001/spellweavers-engine#50]
**Issue:**
Currently there's no clear indication that you have a new turn ready to play (or maybe there is and I don't see it), 
so it is quite hard to know when you need to play

**Comment by BioLogIn001** [comment]
If you are on the match list page, there should be indication near match status in form of [AWAITING ORDERS] message.
If you are on the match page, you either have Submit orders button, or don't, I guess. But also there is [AWAITING ORDERS] message next to the username in the bottom.

All this us very temporary and should be reworked as part of getting a new UI, or course. Which is a major task, let's discuss it on Reddit for now.
